analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.375
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A5A7AA'
    - '#FEC83A'
  rhythmicContrast: 0.4319149
typography_spectrum: 0.4991
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9872341
favicon: null
name: Pronkst√∏k
