favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.375
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A5A7AA'
    - '#FEC83A'
  rhythmicContrast: 0
typography_spectrum: 0.4991
layout_spectrum: 0.9872341
analytics:
  twitter: null
  google: null
  facebook: null
name: Pronkst√∏k
